name: Keep Bot Alive
on:
  schedule:
    - cron: "*/30 * * * *"  # Каждые 30 минут
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Bot
        run: |
          curl -s -o /dev/null https://ваш-проект.onrender.com 