envVars:
  - key: BOT_TOKEN
    value: 7842612175:AAEldaiQtK7YSldUhxx4qVuiIF7jfwTLy10
  - key: RAPIDAPI_KEY
    value: your-actual-rapidapi-key
  - key: BOT_URL
    value: https://your-app-name.onrender.com
